CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
	username TEXT,
	password TEXT,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS items (
	id SERIAL PRIMARY KEY,
	name TEXT,
	amount NUMERIC(10, 2),
	recurring BOOLEAN,
	due_date TIMESTAMPTZ DEFAULT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	creditor TEXT,
	paid BOOLEAN DEFAULT FALSE,
	user_id INTEGER
);

CREATE TABLE IF NOT EXISTS settings (
	id SERIAL PRIMARY KEY,
	user_id INTEGER,
	pay_day TIMESTAMPTZ DEFAULT NULL,
	next_pay_day TIMESTAMPTZ DEFAULT NULL,
	pay_amount NUMERIC(10, 2),
	save_amount NUMERIC(10, 2)
);